namespace BastionVault.IntegrationSdk;

/// <summary>
/// The observability hook (CFG-080, D-M1b-8): fires once per attempt (RES-002), never carrying a
/// body or a token.
/// </summary>
public interface IRequestObserver
{
    /// <summary>Called once per attempt of a logical operation.</summary>
    public void OnRequestCompleted(RequestEvent requestEvent);
}

/// <summary>
/// One attempt's worth of observability data (CFG-080). <see cref="RequestId"/> is generated by the
/// SDK and is stable across the attempts of one logical operation; it is deliberately absent from
/// <see cref="Response"/> (TRN-042) so the hook is the only place it is ever asserted (D-M1b-8).
/// </summary>
public sealed record RequestEvent(
    string Method,
    string Path,
    string Namespace,
    int? StatusCode,
    TimeSpan Duration,
    string RequestId,
    int Attempt,
    string? ErrorCode);
