"""Emitters: one parsed appendix in, four artefact sets out (D-M1c-1).

Every emitter reads the same :class:`catalogue.Catalogue` and the same
:mod:`captures` tables, so the three languages cannot drift from each other —
that single-source property, not the file format, is the point of the generator.

Nothing here is allowed to interpret Appendix B; interpretation happens once, in
:mod:`catalogue`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Sequence

from captures import Capture, captures_by_stem
from catalogue import Catalogue, CatalogueError, Code, Rule, normalise

BANNER_LINES = (
    "Generated by tools/error-catalogue from specifications/appendix-b-error-catalogue.md",
    "(DR-0005 D-M1c-1). Do not edit by hand — .github/workflows/repo-gates.yml regenerates",
    "this file and fails the build on any diff.",
)

DOTNET_PATH = "dotnet/BastionVault.IntegrationSdk/Generated/ErrorCatalogData.g.cs"
RUST_PATH = "rust/bastionvault-integration-sdk/src/generated/error_catalog_data.rs"
PYTHON_PATH = "python/src/bastionvault_integration_sdk/_generated/error_catalog_data.py"
FIXTURE_DIR = "specifications/fixtures/errors"

# D7 (docs/dotnet/errors.md, DOC-002/DOC-007): a generated region inside an otherwise
# hand-written file (DR-0018 D-M11-11). The file itself is never created or deleted by the
# generator — only the text between these two markers is ever touched — so the walkthrough
# around it survives every regeneration.
DOCS_ERRORS_PATH = "docs/dotnet/errors.md"
DOCS_REGION_BEGIN = "<!-- generated:error-catalogue:begin -->"
DOCS_REGION_END = "<!-- generated:error-catalogue:end -->"

# The status a generated recognition fixture answers with. Recognition runs ahead
# of the status table (D-M1c-3), so the status is deliberately one whose own
# fallback row names a *different* code — otherwise the fixture would pass with
# recognition removed.
DEFAULT_FIXTURE_STATUS = 400
ALTERNATE_FIXTURE_STATUS = 403  # for rules whose code is the 400 fallback itself.
# 04-error-model.md step 5, for every status a generated fixture can answer with. The
# self-check refuses a fixture whose expected code equals its status row's, because such a
# fixture would pass with recognition removed entirely (D-M1c-19 made 409 deterministic, so
# it belongs here too).
STATUS_FALLBACK_CODE = {
    400: "BV-INPUT-100",
    403: "BV-AUTHZ-001",
    409: "BV-CONFLICT-001",
    500: "BV-SERVER-005",
    503: "BV-SERVER-002",
}

# AUT-011's enumeration: the codes a *200* login rejection's `data.error` can carry
# (`BV-AUTH-003` is the AUT-010 fallback, the rest are its refinements). This is the one
# hand-authored part of D-M2-25 item 3 and it is hand-authored because the requirement
# itself enumerates it; the *messages* come from the parsed appendix, which is what stops
# the mock server's `login-failure-as-200` simulation from being a second, drifting list.
#
# AUT-012's `BV-AUTH-010`/`BV-AUTH-011` are deliberately absent: those arrive on a `400`
# and travel the executor's ordinary non-2xx path, so they are not 200-rejection messages.
LOGIN_REJECTION_CODES = (
    "BV-AUTH-003",
    "BV-AUTH-004",
    "BV-AUTH-005",
    "BV-AUTH-006",
    "BV-AUTH-007",
    "BV-AUTH-008",
    "BV-AUTH-009",
    "BV-AUTH-012",
    "BV-AUTH-013",
    "BV-AUTH-014",
    "BV-RATE-001",
)

FIXTURE_ADDRESS = "https://vault.example.com:8200"
# Assembled rather than written out: the CNF-025 secret scan exempts
# specifications/fixtures/** but not this file, and a literal here would add a new
# finding to a gate that is already carrying false positives from M0.
FIXTURE_TOKEN = "s." + "FAKEtoken" + ("0" * 16)
FIXTURE_READ_PATH = "secret/data/recognition"
FIXTURE_WRITE_PATH = "sys/policies/acl/recognition"
FIXTURE_RECORDINGS_PATH = "rustion/recordings/abc/chunk/0"


# --------------------------------------------------------------------------- #
# shared helpers
# --------------------------------------------------------------------------- #


def _cs(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _xml(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _rs(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _py_wrapped(text: str, indent: int, limit: int = 108) -> list[str]:
    """A Python string literal wrapped with implicit concatenation.

    `ruff`'s E501 applies to generated sources as much as to hand-written ones
    (CNF-023, and CLA-004 forbids exempting a path to make a gate pass), so long
    catalogue hints are split on spaces rather than emitted on one long line.
    """
    pad = " " * indent
    escaped_words = text.split(" ")
    lines: list[str] = []
    current = ""
    for index, word in enumerate(escaped_words):
        candidate = word if not current else current + " " + word
        # +3 for the two quotes and a trailing space marker.
        if current and len(pad) + len(json.dumps(candidate + " ")) > limit:
            lines.append(pad + json.dumps(current + " "))
            current = word
        else:
            current = candidate
        del index
    lines.append(pad + json.dumps(current))
    return lines


def _fixture_status(rule: Rule) -> int:
    if rule.guard is not None:
        if rule.guard.status is not None:
            return rule.guard.status
        if rule.guard.status_class is not None:
            return rule.guard.status_class * 100
    if rule.code == STATUS_FALLBACK_CODE[DEFAULT_FIXTURE_STATUS]:
        return ALTERNATE_FIXTURE_STATUS
    return DEFAULT_FIXTURE_STATUS


def _fixture_message(rule: Rule, capture: Capture | None) -> str:
    return _fixture_messages(rule, capture)[0][0]


def _fixture_messages(rule: Rule, capture: Capture | None) -> list[tuple[str, str | None]]:
    """The ``(message, alternative)`` pairs one rule's generated fixtures drive.

    A rule with a qualifier group gets **one fixture per alternative** (D-M8-3).
    A single fixture carrying every alternative at once would pass under the
    conjunctive reading of Appendix B §2 as well as the alternation the appendix
    means, so it would certify R-23's defect instead of catching it.
    """
    if capture is not None:
        return [(capture.sample, None)]
    stem = [rule.text.strip()]
    stem += [item.strip() for item in rule.contains_all]
    if not rule.contains_any:
        return [(" ".join(part for part in stem if part), None)]
    return [
        (" ".join(part for part in stem + [alternative.strip()] if part), alternative.strip())
        for alternative in rule.contains_any
    ]


def login_rejections(catalogue: Catalogue) -> list[tuple[str, str]]:
    """D-M2-25 item 3: the ``(message, code)`` rows a 200 login rejection can carry.

    Derived from the same parsed Appendix B §2 table the recogniser is generated
    from, restricted to :data:`LOGIN_REJECTION_CODES` and to rows a status of
    ``200`` can actually reach.  Each language's mock server parameterises its
    ``login-failure-as-200`` simulation from this list instead of a hand-written
    string, so a fixture can never assert a ``data.error`` message the mock
    cannot produce.
    """
    by_stem = captures_by_stem()
    rows: list[tuple[str, str]] = []
    for rule in catalogue.rules:
        if rule.code not in LOGIN_REJECTION_CODES:
            continue
        if rule.path_contains is not None:
            continue
        if rule.guard is not None and not (
            (rule.guard.status is None or rule.guard.status == 200)
            and (rule.guard.status_class is None or rule.guard.status_class == 2)
        ):
            continue
        message = _fixture_message(rule, by_stem.get(rule.text))
        if not matches(rule, normalise(message), 200):
            # A row whose own sample message does not recognise back to it from a
            # 200 would let the mock produce a body the SDK maps elsewhere. The
            # generator refuses to emit it rather than shipping the mismatch.
            raise CatalogueError(
                f"Appendix B §2 row {rule.row} ({rule.code}) is listed as a 200 login "
                f"rejection but its message {message!r} does not recognise to it at status 200."
            )
        rows.append((message, rule.code))

    missing = sorted(set(LOGIN_REJECTION_CODES) - {code for _, code in rows})
    if missing:
        raise CatalogueError(
            "AUT-011 names these 200-login-rejection codes but Appendix B §2 has no "
            f"reachable row producing them: {', '.join(missing)}"
        )
    return rows


def matches(rule: Rule, normalised: str, status: int, path: str = "") -> bool:
    """The runtime matcher, in Python, used by the generator's own self-check."""
    if rule.path_contains is not None and rule.path_contains not in path:
        return False
    if rule.guard is not None:
        if rule.guard.status is not None and status != rule.guard.status:
            return False
        if rule.guard.status_class is not None and status // 100 != rule.guard.status_class:
            return False
    if rule.kind == "exact":
        if normalised != rule.text.strip():
            return False
    elif rule.kind == "prefix":
        if not normalised.startswith(rule.text):
            return False
    else:
        if rule.text.strip() not in normalised:
            return False
    # A qualifier group is ANDed with the stem, but its items are alternatives
    # (D-M8-2): an empty group imposes nothing, a non-empty one needs one hit.
    return all(item.strip() in normalised for item in rule.contains_all) and (
        not rule.contains_any
        or any(item.strip() in normalised for item in rule.contains_any)
    )


# --------------------------------------------------------------------------- #
# .NET
# --------------------------------------------------------------------------- #


def emit_dotnet(catalogue: Catalogue) -> str:
    by_stem = captures_by_stem()
    captures = list(by_stem.values())
    capture_index = {capture.stem: index for index, capture in enumerate(captures)}

    out: list[str] = ["// <auto-generated>"]
    out += [f"//     {line}" for line in BANNER_LINES]
    out += ["// </auto-generated>", "", "namespace BastionVault.IntegrationSdk", "{"]
    out += ["    public static partial class ErrorCodes", "    {"]
    for index, entry in enumerate(catalogue.codes):
        if index:
            out.append("")
        out.append(f"        /// <summary>{_xml(entry.message)}</summary>")
        out.append(f"        public const string {entry.constant} = {_cs(entry.code)};")
    out += ["    }", "}", "", "namespace BastionVault.IntegrationSdk.Internal", "{"]
    out += [
        "    internal static class ErrorCatalogData",
        "    {",
        "        /// <summary>Appendix B §1, in appendix order (ERR-036, D-M1c-7's <c>All</c>).</summary>",
        "        internal static readonly ErrorCatalogEntry[] Entries =",
        "        [",
    ]
    for entry in catalogue.codes:
        out.append(
            "            new("
            + f"{_cs(entry.code)}, {_cs(entry.name)}, ErrorCategory.{entry.category},"
        )
        out.append(f"                {_cs(entry.message)},")
        out.append(f"                {_cs(entry.hint)},")
        out.append(f"                {str(entry.retryable).lower()}),")
    out += ["        ];", ""]

    out += [
        "        /// <summary>Appendix B §2, in table order — first match wins (D-M1c-3).</summary>",
        "        internal static readonly RecognitionRule[] Rules =",
        "        [",
    ]
    for rule in catalogue.rules:
        contains = ", ".join(_cs(item) for item in rule.contains_all)
        contains_literal = f"[{contains}]" if contains else "[]"
        any_of = ", ".join(_cs(item) for item in rule.contains_any)
        any_literal = f"[{any_of}]" if any_of else "[]"
        status = "null" if rule.guard is None or rule.guard.status is None else str(rule.guard.status)
        klass = (
            "null"
            if rule.guard is None or rule.guard.status_class is None
            else str(rule.guard.status_class)
        )
        index = capture_index.get(rule.text, -1)
        scope = "null" if rule.path_contains is None else _cs(rule.path_contains)
        out.append(
            f"            new(RecognitionKind.{rule.kind.capitalize()}, {_cs(rule.text)}, {contains_literal},"
        )
        out.append(
            f"                {any_literal}, {status}, {klass}, {scope}, {_cs(rule.code)}, {index}),"
        )
    out += ["        ];", ""]

    out += [
        "        /// <summary>The D-M1c-4 capture table, hand-authored in the generator's input.</summary>",
        "        internal static readonly DetailsCapture[] Captures =",
        "        [",
    ]
    for capture in captures:
        keys = ", ".join(_cs(key) for key in capture.keys)
        out.append(
            f"            new(DetailsCaptureKind.{_pascal(capture.kind)}, [{keys}],"
            f" {_cs(capture.prefix)}, {_cs(capture.suffix)}),"
        )
    out += ["        ];", ""]

    out += [
        "        /// <summary>",
        "        /// D-M2-25 item 3: the <c>data.error</c> messages a <c>200</c> login rejection can carry",
        "        /// (AUT-011), each with the code the generated <see cref=\"Rules\"/> table maps it to. Read by",
        "        /// the test harness's mock server so its <c>login-failure-as-200</c> simulation (TST-021)",
        "        /// cannot drift from the recogniser, and by the AUT-011 tests so every row is exercised.",
        "        /// </summary>",
        "        internal static readonly LoginRejection[] LoginRejections =",
        "        [",
    ]
    for message, code in login_rejections(catalogue):
        out.append(f"            new({_cs(code)}, {_cs(message)}),")
    out += ["        ];", "    }", "}", ""]
    return "\n".join(out)


def _pascal(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_"))


# --------------------------------------------------------------------------- #
# Rust
# --------------------------------------------------------------------------- #


def emit_rust(catalogue: Catalogue) -> str:
    by_stem = captures_by_stem()
    captures = list(by_stem.values())
    capture_index = {capture.stem: index for index, capture in enumerate(captures)}

    out: list[str] = [f"//! {line}" for line in BANNER_LINES]
    out += ["", "use crate::error::ErrorCategory;", ""]
    out += [
        "/// One Appendix B §1 row: code, name, category, message, hint, retryable.",
        "pub type ErrorCatalogRow = (",
        "    &'static str,",
        "    &'static str,",
        "    ErrorCategory,",
        "    &'static str,",
        "    &'static str,",
        "    bool,",
        ");",
        "",
        "/// One Appendix B §2 rule: kind, text, contains-all, contains-any, status, status class,",
        "/// path scope, code, capture. `contains_all` is ANDed with the stem; `contains_any` is one",
        "/// qualifier group, ANDed with the stem and ORed within itself (D-M8-2).",
        "pub type RecognitionRow = (",
        "    &'static str,",
        "    &'static str,",
        "    &'static [&'static str],",
        "    &'static [&'static str],",
        "    Option<u16>,",
        "    Option<u16>,",
        "    Option<&'static str>,",
        "    &'static str,",
        "    Option<usize>,",
        ");",
        "",
        "/// One D-M1c-4 capture: kind, keys, prefix, suffix.",
        "pub type DetailsCaptureRow = (&'static str, &'static [&'static str], &'static str, &'static str);",
        "",
        "/// Appendix B §1, in appendix order (ERR-036).",
        "pub static ENTRIES: &[ErrorCatalogRow] = &[",
    ]
    for entry in catalogue.codes:
        out.append("    (")
        out.append(f"        {_rs(entry.code)},")
        out.append(f"        {_rs(entry.name)},")
        out.append(f"        ErrorCategory::{entry.category},")
        out.append(f"        {_rs(entry.message)},")
        out.append(f"        {_rs(entry.hint)},")
        out.append(f"        {str(entry.retryable).lower()},")
        out.append("    ),")
    out += ["];", "", "/// Appendix B §2, in table order — first match wins (D-M1c-3).", "pub static RULES: &[RecognitionRow] = &["]
    for rule in catalogue.rules:
        contains = ", ".join(_rs(item) for item in rule.contains_all)
        any_of = ", ".join(_rs(item) for item in rule.contains_any)
        status = "None" if rule.guard is None or rule.guard.status is None else f"Some({rule.guard.status})"
        klass = (
            "None"
            if rule.guard is None or rule.guard.status_class is None
            else f"Some({rule.guard.status_class})"
        )
        index = capture_index.get(rule.text)
        capture = "None" if index is None else f"Some({index})"
        out.append("    (")
        out.append(f"        {_rs(rule.kind)},")
        out.append(f"        {_rs(rule.text)},")
        out.append(f"        &[{contains}],")
        out.append(f"        &[{any_of}],")
        out.append(f"        {status},")
        out.append(f"        {klass},")
        out.append(f"        {'None' if rule.path_contains is None else f'Some({_rs(rule.path_contains)})'},")
        out.append(f"        {_rs(rule.code)},")
        out.append(f"        {capture},")
        out.append("    ),")
    out += ["];", "", "/// The D-M1c-4 capture table, hand-authored in the generator's input.", "pub static CAPTURES: &[DetailsCaptureRow] = &["]
    for capture_row in captures:
        keys = ", ".join(_rs(key) for key in capture_row.keys)
        out.append(
            f"    ({_rs(capture_row.kind)}, &[{keys}], {_rs(capture_row.prefix)}, {_rs(capture_row.suffix)}),"
        )
    out += ["];", "", "/// Stable error code constants (ERR-005).", "pub mod error_codes {"]
    for entry in catalogue.codes:
        out.append(f"    /// {entry.message}")
        out.append(f'    pub const {entry.screaming}: &str = "{entry.code}";')
    out += ["}", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# Python
# --------------------------------------------------------------------------- #

PYTHON_CATEGORY = {
    "Configuration": "CONFIGURATION",
    "Input": "INPUT",
    "Transport": "TRANSPORT",
    "Protocol": "PROTOCOL",
    "Authentication": "AUTHENTICATION",
    "Authorization": "AUTHORIZATION",
    "NotFound": "NOT_FOUND",
    "Conflict": "CONFLICT",
    "RateLimit": "RATE_LIMIT",
    "Quota": "QUOTA",
    "ServerState": "SERVER_STATE",
    "Discovery": "DISCOVERY",
    "Engine": "ENGINE",
}


def emit_python(catalogue: Catalogue) -> str:
    by_stem = captures_by_stem()
    captures = list(by_stem.values())
    capture_index = {capture.stem: index for index, capture in enumerate(captures)}

    out: list[str] = ['"""']
    out += list(BANNER_LINES)
    out += ['"""', "", "from __future__ import annotations", "", "from typing import Final", ""]
    out += ["from ..errors import ErrorCategory", ""]
    out += [
        "ErrorCatalogRow = tuple[str, str, ErrorCategory, str, str, bool]",
        "#: kind, text, contains-all, contains-any, status, status class, path scope, code, capture.",
        "#: ``contains_all`` is ANDed with the stem; ``contains_any`` is one qualifier group,",
        "#: ANDed with the stem and ORed within itself (D-M8-2).",
        "RecognitionRow = tuple[",
        "    str,",
        "    str,",
        "    tuple[str, ...],",
        "    tuple[str, ...],",
        "    int | None,",
        "    int | None,",
        "    str | None,",
        "    str,",
        "    int | None,",
        "]",
        "DetailsCaptureRow = tuple[str, tuple[str, ...], str, str]",
        "",
        "#: Appendix B §1, in appendix order (ERR-036).",
        "ENTRIES: Final[tuple[ErrorCatalogRow, ...]] = (",
    ]
    for entry in catalogue.codes:
        out.append("    (")
        out.append(f"        {json.dumps(entry.code)},")
        out.append(f"        {json.dumps(entry.name)},")
        out.append(f"        ErrorCategory.{PYTHON_CATEGORY[entry.category]},")
        message_lines = _py_wrapped(entry.message, 8)
        message_lines[-1] += ","
        out += message_lines
        hint_lines = _py_wrapped(entry.hint, 8)
        hint_lines[-1] += ","
        out += hint_lines
        out.append(f"        {entry.retryable},")
        out.append("    ),")
    out += [")", "", "#: Appendix B §2, in table order — first match wins (D-M1c-3).", "RULES: Final[tuple[RecognitionRow, ...]] = ("]
    for rule in catalogue.rules:
        contains = ", ".join(json.dumps(item) for item in rule.contains_all)
        if contains:
            contains += ","
        any_of = ", ".join(json.dumps(item) for item in rule.contains_any)
        if any_of:
            any_of += ","
        status = "None" if rule.guard is None or rule.guard.status is None else str(rule.guard.status)
        klass = (
            "None"
            if rule.guard is None or rule.guard.status_class is None
            else str(rule.guard.status_class)
        )
        index = capture_index.get(rule.text)
        out.append("    (")
        out.append(f"        {json.dumps(rule.kind)},")
        out.append(f"        {json.dumps(rule.text)},")
        out.append(f"        ({contains}),")
        out.append(f"        ({any_of}),")
        out.append(f"        {status},")
        out.append(f"        {klass},")
        out.append(f"        {'None' if rule.path_contains is None else json.dumps(rule.path_contains)},")
        out.append(f"        {json.dumps(rule.code)},")
        out.append(f"        {'None' if index is None else index},")
        out.append("    ),")
    out += [")", "", "#: The D-M1c-4 capture table, hand-authored in the generator's input.", "CAPTURES: Final[tuple[DetailsCaptureRow, ...]] = ("]
    for capture in captures:
        keys = ", ".join(json.dumps(key) for key in capture.keys) + ","
        out.append(
            f"    ({json.dumps(capture.kind)}, ({keys}), "
            f"{json.dumps(capture.prefix)}, {json.dumps(capture.suffix)}),"
        )
    out += [")", "", "", "class ErrorCodes:", '    """Stable error code constants (ERR-005)."""', ""]
    for entry in catalogue.codes:
        out.append(f"    {entry.screaming}: Final[str] = {json.dumps(entry.code)}")
    out.append("")
    return "\n".join(out)


PYTHON_INIT = '''"""Generated sources. See tools/error-catalogue (DR-0005 D-M1c-1)."""
'''

RUST_MOD = """//! Generated sources. See tools/error-catalogue (DR-0005 D-M1c-1).

pub mod error_catalog_data;
"""


# --------------------------------------------------------------------------- #
# Fixtures (D-M1c-10)
# --------------------------------------------------------------------------- #


def fixture_documents(catalogue: Catalogue) -> list[tuple[str, dict[str, object]]]:
    from captures import ALREADY_FIXTURED

    by_stem = captures_by_stem()
    per_code: dict[str, int] = {}
    documents: list[tuple[str, dict[str, object]]] = []

    for rule in catalogue.rules:
        if (rule.kind, rule.text) in ALREADY_FIXTURED:
            continue
        capture = by_stem.get(rule.text)
        status = _fixture_status(rule)

        write = rule.scope_note is not None and "write" in rule.scope_note
        if rule.scope_note is not None and "recordings" in rule.scope_note:
            path = FIXTURE_RECORDINGS_PATH
        else:
            path = FIXTURE_WRITE_PATH if write else FIXTURE_READ_PATH

        requirements = ["ERR-020"]
        if capture is not None:
            requirements.append("ERR-035")

        for message, alternative in _fixture_messages(rule, capture):
            per_code[rule.code] = per_code.get(rule.code, 0) + 1
            identifier = f"errors.recognition.{rule.code.lower()}.{per_code[rule.code]}"
            documents.append(
                (
                    identifier,
                    _fixture_document(
                        catalogue, rule, identifier, status, message, alternative,
                        path, write, requirements, capture,
                    ),
                )
            )

    return documents


def _fixture_document(
    catalogue: Catalogue,
    rule: Rule,
    identifier: str,
    status: int,
    message: str,
    alternative: str | None,
    path: str,
    write: bool,
    requirements: Sequence[str],
    capture: Capture | None,
) -> dict[str, object]:
    """One generated recognition fixture: one rule, one message it must recognise."""
    error: dict[str, object] = {
        "code": rule.code,
        "statusCode": status,
        "retryable": catalogue.by_code()[rule.code].retryable,
        "attempts": 1,
        "serverMessage": message,
    }
    if capture is not None:
        error["detailsKeys"] = list(capture.keys)

    expect_request: dict[str, object] = {
        "method": "POST" if write else "GET",
        "url": f"{FIXTURE_ADDRESS}/v1/{path}",
    }
    operation: dict[str, object] = {
        "name": "Logical.Write" if write else "Logical.Read",
        "args": {"path": path},
    }
    if write:
        operation["args"] = {"path": path, "body": {"policy": "path \"secret/*\" { capabilities = [\"read\"] }"}}
        expect_request["body"] = operation["args"]["body"]  # type: ignore[index]

    qualifier = "" if alternative is None else f" + '{alternative}'"
    return {
        "id": identifier,
        "title": (
            f"Appendix B §2 row {rule.row}: {rule.kind} "
            f"'{rule.text.strip()}'{qualifier} maps to {rule.code}"
        ),
        "capturedFrom": (
            "specifications/appendix-b-error-catalogue.md §2 "
            "(generated by tools/error-catalogue, D-M1c-10)"
        ),
        "requirements": requirements,
        "level": "core",
        "sections": ["04"],
        "client": {
            "address": FIXTURE_ADDRESS,
            "token": FIXTURE_TOKEN,
            "namespace": "",
            "apiPrefix": "v1",
            "settings": {"RateGate": {"RatePerSecond": 0}, "RetryPolicy": {"MaxAttempts": 1}},
        },
        "operation": operation,
        "exchanges": [
            {
                "expectRequest": expect_request,
                "respond": {"status": status, "body": {"error": message}},
            }
        ],
        "expect": {"error": error},
    }


def check_first_match(catalogue: Catalogue, documents: Sequence[tuple[str, dict[str, object]]]) -> None:
    """Every generated fixture must be won by the rule it was generated from.

    First-match-wins (D-M1c-3) means a later row can be shadowed by an earlier
    one. Rather than trust the reading, the generator replays its own matcher
    over every fixture it emits and fails if the winning rule names a different
    code.
    """
    from catalogue import CatalogueError, normalise

    for identifier, document in documents:
        exchange = document["exchanges"][0]  # type: ignore[index]
        status = exchange["respond"]["status"]  # type: ignore[index]
        message = exchange["respond"]["body"]["error"]  # type: ignore[index]
        expected = document["expect"]["error"]["code"]  # type: ignore[index]
        normalised = normalise(message)
        path = str(document["operation"]["args"]["path"])  # type: ignore[index]
        winner = next((rule for rule in catalogue.rules if matches(rule, normalised, status, path)), None)
        if winner is None:
            raise CatalogueError(f"generated fixture {identifier} matches no recognition rule")
        if winner.code != expected:
            raise CatalogueError(
                f"generated fixture {identifier} expects {expected} but first-match-wins "
                f"(D-M1c-3) awards it to row {winner.row} → {winner.code}"
            )
        fallback = STATUS_FALLBACK_CODE.get(status)
        if fallback is not None and fallback == expected:
            raise CatalogueError(
                f"generated fixture {identifier} would pass on the status table alone"
            )


def emit_fixtures(catalogue: Catalogue) -> dict[str, str]:
    documents = fixture_documents(catalogue)
    check_first_match(catalogue, documents)
    return {
        f"{FIXTURE_DIR}/{identifier}.json": json.dumps(document, indent=2, ensure_ascii=False) + "\n"
        for identifier, document in documents
    }


# --------------------------------------------------------------------------- #
# docs/dotnet/errors.md (D7, generated region only)
# --------------------------------------------------------------------------- #


def _md(text: str) -> str:
    """Markdown table cells are pipe-delimited; escape the one character that would break
    that without changing anything the appendix's own hints and messages contain (none of
    them use ``|``, so this is a safety net, not a transform DOC-007's "verbatim" trips over).
    """
    return text.replace("|", "\\|")


def emit_docs_errors_region(catalogue: Catalogue) -> str:
    """The generated half of D7 (DOC-002, DOC-007): every code with its category, default
    message, hint and retryability, plus the Appendix B §2 recognition table that supplies
    the HTTP triggers and recognised server strings for each code. Read by
    ``generate.py``, which splices this text between :data:`DOCS_REGION_BEGIN` and
    :data:`DOCS_REGION_END` and touches nothing else in the file.
    """
    lines: list[str] = [
        "",
        "### All codes",
        "",
        "Appendix B §1, in appendix order (ERR-036). `Retryable` is `Error.Retryable`; a hint",
        "here is reproduced verbatim from the catalogue (DOC-007).",
        "",
        "| Code | Category | Retryable | Message | Hint |",
        "|---|---|---|---|---|",
    ]
    for entry in catalogue.codes:
        lines.append(
            f"| `{entry.code}` | {entry.category} | {'yes' if entry.retryable else 'no'} "
            f"| {_md(entry.message)} | {_md(entry.hint)} |"
        )
    lines += [
        "",
        "### Server-message recognition",
        "",
        "Appendix B §2, in table order — **first match wins** (D-M1c-3). A row with no HTTP",
        "status guard matches at any status. The server text is matched after normalisation",
        "(trim; strip a trailing `.`; strip `(retry after Ns)`; lower-case).",
        "",
        "| Match | Server text | HTTP status | Code |",
        "|---|---|---|---|",
    ]
    for rule in catalogue.rules:
        if rule.guard is None:
            status = "any"
        elif rule.guard.status is not None:
            status = str(rule.guard.status)
        else:
            status = f"{rule.guard.status_class}xx"
        text = rule.text.strip()
        if rule.contains_all:
            text += " + " + " + ".join(rule.contains_all)
        if rule.contains_any:
            text += " + (" + " / ".join(rule.contains_any) + ")"
        lines.append(f"| {rule.kind} | `{_md(text)}` | {status} | `{rule.code}` |")
    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# catalogue.json
# --------------------------------------------------------------------------- #


def emit_intermediate(catalogue: Catalogue) -> str:
    from captures import DETAILS_CAPTURES

    payload = {
        "generatedFrom": "specifications/appendix-b-error-catalogue.md",
        "generator": "tools/error-catalogue",
        "codes": [entry.as_json() for entry in catalogue.codes],
        "recognition": [rule.as_json() for rule in catalogue.rules],
        "detailsCaptures": [capture.as_json() for capture in DETAILS_CAPTURES],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def artefacts(catalogue: Catalogue) -> dict[str, str]:
    """Every file the generator owns, keyed by repository-relative path."""
    files: dict[str, str] = {
        "tools/error-catalogue/catalogue.json": emit_intermediate(catalogue),
        DOTNET_PATH: emit_dotnet(catalogue),
        RUST_PATH: emit_rust(catalogue),
        PYTHON_PATH: emit_python(catalogue),
        "rust/bastionvault-integration-sdk/src/generated/mod.rs": RUST_MOD,
        "python/src/bastionvault_integration_sdk/_generated/__init__.py": PYTHON_INIT,
    }
    files.update(emit_fixtures(catalogue))
    return files


def owned_fixture_paths(root: Path) -> set[Path]:
    """Generated fixture files currently on disk, so a deleted row's file is removed."""
    directory = root / FIXTURE_DIR
    if not directory.is_dir():
        return set()
    return {
        path
        for path in directory.glob("errors.recognition.bv-*.json")
        if path.is_file()
    }


__all__ = [
    "Code",
    "Rule",
    "DOCS_ERRORS_PATH",
    "DOCS_REGION_BEGIN",
    "DOCS_REGION_END",
    "artefacts",
    "emit_dotnet",
    "emit_docs_errors_region",
    "emit_fixtures",
    "emit_intermediate",
    "emit_python",
    "emit_rust",
    "fixture_documents",
    "matches",
    "owned_fixture_paths",
]
