using System.Text.RegularExpressions;
using BastionVault.IntegrationSdk.Tests.Harness;

namespace BastionVault.IntegrationSdk.Tests;

/// <summary>
/// D7's drift gate (<c>docs/dotnet/errors.md</c>'s "All codes" table), generated by
/// <c>tools/error-catalogue/emitters.py</c> from <c>specifications/appendix-b-error-catalogue.md</c>
/// and enforced in CI by regenerate-then-<c>git diff --exit-code</c>. This class is the in-build
/// half of that gate: it reflects on <see cref="ErrorCatalog"/>.All directly, so DOC-007 and the
/// D7 limb of DOC-002/DOC-024 are verified by a test, not only by a CI step.
/// </summary>
public sealed class ErrorDocsDriftTests
{
    private static string RepositoryRoot { get; } = new FixtureRepository().RepositoryRoot;

    private static string ErrorDocText { get; } =
        File.ReadAllText(Path.Combine(RepositoryRoot, "docs", "dotnet", "errors.md"));

    private static IReadOnlyDictionary<string, DocRow> DocumentedRows { get; } = ParseAllCodesTable();

    [Trait("Requirement", "DOC-002")]
    [Trait("Requirement", "DOC-024")]
    [Fact]
    public void Every_catalogue_code_appears_in_D7_and_vice_versa()
    {
        string[] code = [.. ErrorCatalog.All.Select(entry => entry.Code).OrderBy(name => name, StringComparer.Ordinal)];
        string[] documented = [.. DocumentedRows.Keys.OrderBy(name => name, StringComparer.Ordinal)];

        string[] missingFromDocs = [.. code.Except(documented, StringComparer.Ordinal)];
        string[] missingFromCode = [.. documented.Except(code, StringComparer.Ordinal)];

        Assert.True(
            missingFromDocs.Length == 0 && missingFromCode.Length == 0,
            "docs/dotnet/errors.md's 'All codes' table has drifted from ErrorCatalog.All.\n"
                + "In the catalogue but not documented: " + string.Join(", ", missingFromDocs) + "\n"
                + "Documented but not in the catalogue: " + string.Join(", ", missingFromCode));
    }

    [Trait("Requirement", "DOC-002")]
    [Trait("Requirement", "DOC-007")]
    [Trait("Requirement", "DOC-024")]
    [Fact]
    public void Every_documented_hint_is_the_catalogue_hint_verbatim()
    {
        List<string> failures = [];
        foreach (ErrorCatalogEntry entry in ErrorCatalog.All)
        {
            if (!DocumentedRows.TryGetValue(entry.Code, out DocRow row))
            {
                continue; // reported by the symmetry test above
            }

            if (!string.Equals(row.Hint, entry.Hint, StringComparison.Ordinal))
            {
                failures.Add(
                    $"{entry.Code}: catalogue hint `{entry.Hint}` does not match the documented hint `{row.Hint}`.");
            }
        }

        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    [Trait("Requirement", "DOC-002")]
    [Trait("Requirement", "DOC-024")]
    [Fact]
    public void Every_documented_message_and_category_and_retryability_match_the_catalogue()
    {
        List<string> failures = [];
        foreach (ErrorCatalogEntry entry in ErrorCatalog.All)
        {
            if (!DocumentedRows.TryGetValue(entry.Code, out DocRow row))
            {
                continue; // reported by the symmetry test above
            }

            if (!string.Equals(row.Message, entry.Message, StringComparison.Ordinal))
            {
                failures.Add(
                    $"{entry.Code}: catalogue message `{entry.Message}` does not match the documented message `{row.Message}`.");
            }

            if (!string.Equals(row.Category, entry.Category.ToString(), StringComparison.Ordinal))
            {
                failures.Add(
                    $"{entry.Code}: catalogue category `{entry.Category}` does not match the documented category `{row.Category}`.");
            }

            bool? documentedRetryable = row.Retryable switch
            {
                "yes" => true,
                "no" => false,
                _ => null,
            };

            if (documentedRetryable is null)
            {
                failures.Add($"{entry.Code}: documented Retryable column `{row.Retryable}` is neither `yes` nor `no`.");
            }
            else if (documentedRetryable != entry.Retryable)
            {
                failures.Add(
                    $"{entry.Code}: catalogue Retryable is `{entry.Retryable}` but the document says `{row.Retryable}`.");
            }
        }

        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    // ------------------------------------------------------------------ //
    // docs-side extraction
    // ------------------------------------------------------------------ //

    private readonly record struct DocRow(string Category, string Retryable, string Message, string Hint);

    private static Dictionary<string, DocRow> ParseAllCodesTable()
    {
        string section = Section(ErrorDocText, "### All codes", "### Server-message recognition");
        Dictionary<string, DocRow> rows = new(StringComparer.Ordinal);
        foreach (string line in section.Split('\n'))
        {
            (string code, DocRow row)? parsed = ParseRow(line);
            if (parsed is { } entry)
            {
                rows[entry.code] = entry.row;
            }
        }

        return rows;
    }

    private static (string code, DocRow row)? ParseRow(string line)
    {
        string trimmed = line.Trim();
        if (trimmed.Length < 2 || trimmed[0] != '|' || trimmed[^1] != '|')
        {
            return null;
        }

        string[] cells = [.. trimmed[1..^1].Split('|').Select(cell => cell.Trim())];
        if (cells.Length != 5)
        {
            return null;
        }

        Match codeMatch = Regex.Match(cells[0], @"^`(BV-[A-Z]+-\d+)`$");
        if (!codeMatch.Success)
        {
            return null;
        }

        return (codeMatch.Groups[1].Value, new DocRow(cells[1], cells[2], cells[3], cells[4]));
    }

    private static string Section(string text, string heading, string? nextHeading)
    {
        int start = text.IndexOf(heading, StringComparison.Ordinal);
        if (start < 0)
        {
            throw new InvalidOperationException("docs/dotnet/errors.md has no '" + heading + "' heading");
        }

        start += heading.Length;
        int end = nextHeading is null ? text.Length : text.IndexOf(nextHeading, start, StringComparison.Ordinal);
        if (end < 0)
        {
            end = text.Length;
        }

        return text[start..end];
    }
}
