[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bastionvault-integration-sdk"
version = "0.2.1"
description = "BastionVault Integration SDK base Python package"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "BastionVault" }]

[tool.setuptools.packages.find]
where = ["src"]
