"""Member-level public-API surface extractor for CNF-027 (D-M1c-22).

Replaces the earlier name-only baseline (`sorted(sdk.__all__)`) with one line per
public class, method, property, dataclass field, enum member and constant *value* --
the granularity `dotnet/BastionVault.IntegrationSdk.Tests/ApiSurface/
PublicApiSurfaceScanner.cs` (reflection) and `rust/.../public-api-baseline.txt`
(rustdoc) already run. `ErrorCodes` is a plain class of `Final[str]` constants: a
rename that keeps the constant's *name* the same but changes its *value* was
previously invisible (D-M1c-21) because the old baseline only ever recorded names.

Scope is the transitive closure over `bastionvault_integration_sdk.__all__`, not
`__all__` itself (decision, brief requirement 2): starting from every name in
`__all__`, any *public* class *defined inside this package* that is reachable through
a public member's resolved parameter or return annotation is also captured. This is
what pulls in `Logical` (`client.py:Client.logical` returns it), which is public but
not exported in `__all__`.

Public instance attributes are captured too (`self.X = ...` and `self.X: T = ...` found
by walking the AST of `__init__` and of every other public method a class declares --
never by instantiating; `BastionVaultError.__init__` is keyword-only with 5 required
arguments, so instantiation is not an option). Type inference runs exactly three rules,
in order: (a) an annotated assignment's own annotation, evaluated in the defining
module's namespace and rendered through `render_type`, or the `ast.unparse` source text
verbatim on any resolution failure; (b) an unannotated assignment whose value is a bare
name matching a parameter of the enclosing method uses that parameter's rendered
annotation; (c) anything else -- a call, a `BoolOp`, an attribute access -- is the
`_UNRESOLVED` sentinel. A name already emitted as a property, dataclass field, enum
member or constant is not emitted again as an attribute. The kind word is `attribute`,
not `property`: an instance attribute is read/write with no getter contract, so reusing
`property` for a byte-level look-alike with the .NET baseline would assert something
false.

Rendering never calls `repr()` on a typing object -- `repr()` of `typing`/`types`
constructs is not stable across interpreter versions and would make this gate flake
between the 3.11/3.12/3.14 interpreters this repository is developed and tested with.
Every annotation is walked and rendered by hand instead (`render_type`). The whole
package uses `from __future__ import annotations`, so annotations arrive as strings;
`inspect.signature(..., eval_str=True)` resolves them into real objects wherever
possible. Where resolution fails (a name only imported under `TYPE_CHECKING`, such as
`Logical.__init__`'s `client: Client` parameter), the source text is emitted verbatim
instead of crashing.

Usage::

    python -m tests._api_surface_extractor            # print the regenerated baseline
    python -m tests._api_surface_extractor --write     # write python/api_surface.txt

Named with a leading underscore so pytest's `test_*.py` collection glob never picks
this module up as a test module in its own right; `tests/test_api_surface.py` is the
gate that runs it.
"""

from __future__ import annotations

import ast
import dataclasses
import inspect
import sys
import textwrap
import types
import typing
from collections.abc import Iterable, Mapping
from enum import Enum
from pathlib import Path
from typing import Any, Final

# Importable without `pip install -e` and without a pre-set `PYTHONPATH`: this mirrors
# the `PYTHONPATH=./python/src` shape from the verification contract (agents.md §9)
# rather than depending on the package already being installed in the environment.
_SRC_DIR = Path(__file__).resolve().parents[1] / "src"
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

import bastionvault_integration_sdk as _sdk  # noqa: E402

_PACKAGE = "bastionvault_integration_sdk"
_BASELINE_PATH = Path(__file__).resolve().parents[1] / "api_surface.txt"
_HEADER = (
    "# Mechanically generated by tests/_api_surface_extractor.py (D-M1c-22). "
    "Do not hand-edit."
)
_UNRESOLVED: Final[str] = "<unresolved>"
_SCALAR_CONSTANT_TYPES: Final[tuple[type, ...]] = (str, int, float, bool, bytes, tuple)


def _is_public(name: str) -> bool:
    return not name.startswith("_")


def _is_package_class(obj: object) -> bool:
    return isinstance(obj, type) and obj.__module__.startswith(_PACKAGE)


def _canonical_name(cls: type) -> str:
    """The stable, flat name a class is documented under.

    Package classes are documented under the flat `bastionvault_integration_sdk.<Name>`
    form regardless of which internal submodule defines them (mirroring the flat
    `BastionVault.IntegrationSdk` namespace the .NET scanner records), so moving a class
    between internal modules is not, by itself, a surface change.
    """

    if _is_package_class(cls):
        return f"{_PACKAGE}.{cls.__qualname__}"
    if cls.__module__ == "builtins":
        return cls.__qualname__
    return f"{cls.__module__}.{cls.__qualname__}"


def render_type(annotation: Any) -> str:
    """Render a resolved (or unresolved) annotation into one canonical string.

    Never `repr()`s a typing object. A `str` annotation is source text that
    `eval_str=True` could not resolve (e.g. a `TYPE_CHECKING`-only import); it is
    emitted verbatim.
    """

    if annotation is inspect.Signature.empty:
        return _UNRESOLVED
    if annotation is None or annotation is type(None):
        return "None"
    if annotation is Ellipsis:
        return "..."
    if annotation is typing.Any:
        return "typing.Any"
    if isinstance(annotation, str):
        return annotation

    origin = typing.get_origin(annotation)
    if origin is types.UnionType or origin is typing.Union:
        return " | ".join(render_type(arg) for arg in typing.get_args(annotation))
    if origin is not None:
        args = typing.get_args(annotation)
        base = _canonical_name(origin) if isinstance(origin, type) else str(origin)
        if not args:
            return base
        return f"{base}[{', '.join(render_type(arg) for arg in args)}]"

    if isinstance(annotation, type):
        return _canonical_name(annotation)

    # A TypeVar or another exotic annotation form: fall back to its plain name rather
    # than a typing repr().
    return getattr(annotation, "__name__", str(annotation))


def _collect_referenced_classes(annotation: Any, found: set[type]) -> None:
    if isinstance(annotation, type):
        found.add(annotation)
        return
    origin = typing.get_origin(annotation)
    if origin is not None:
        for arg in typing.get_args(annotation):
            _collect_referenced_classes(arg, found)


def _resolved_signature(func: Any) -> tuple[inspect.Signature, bool]:
    """`(signature, resolved)`. `resolved=False` means annotations are raw source text."""

    try:
        return inspect.signature(func, eval_str=True), True
    except (NameError, TypeError):
        return inspect.signature(func, eval_str=False), False


def _own_callables(cls: type) -> Iterable[tuple[str, Any, str]]:
    """`(name, underlying function, label)` for every public callable `cls` declares.

    Declared-only (`cls.__dict__`, not inherited), mirroring the .NET scanner's
    `BindingFlags.DeclaredOnly` (`PublicApiSurfaceScanner.cs`).
    """

    is_protocol = getattr(cls, "_is_protocol", False)
    for name, member in cls.__dict__.items():
        if not _is_public(name) and name != "__init__":
            continue
        if name == "__init__" and is_protocol:
            # `typing.Protocol` synthesizes a structural, non-instantiable
            # `__init__(*args, **kwargs)` on every Protocol subclass (a typing
            # implementation detail, not a member the type actually declares).
            continue
        if isinstance(member, staticmethod):
            yield name, member.__func__, "staticmethod"
        elif isinstance(member, classmethod):
            yield name, member.__func__, "classmethod"
        elif isinstance(member, property):
            continue  # handled by `_own_properties`
        elif inspect.isfunction(member):
            label = "async method" if inspect.iscoroutinefunction(member) else "method"
            yield name, member, label


def _own_properties(cls: type) -> Iterable[tuple[str, property]]:
    for name, member in cls.__dict__.items():
        if _is_public(name) and isinstance(member, property):
            yield name, member


def _own_dataclass_fields(cls: type) -> Iterable[tuple[dataclasses.Field[Any], Any, bool]]:
    if not dataclasses.is_dataclass(cls):
        return
    own_field_names = set(cls.__dict__.get("__dataclass_fields__", {}).keys())
    try:
        hints: dict[str, Any] | None = typing.get_type_hints(cls)
    except Exception:  # noqa: BLE001 - any resolution failure means "fall back to source text"
        hints = None
    for field in dataclasses.fields(cls):
        if field.name not in own_field_names or not _is_public(field.name):
            continue
        if hints is not None and field.name in hints:
            yield field, hints[field.name], True
        else:
            yield field, field.type, False


def _own_constants(cls: type) -> Iterable[tuple[str, Any]]:
    """Public class-level scalar attribute values, e.g. every `ErrorCodes` member.

    Excludes dataclass field names: a dataclass field with a plain (non-factory)
    default stores that default as a class attribute of the same name, which is a
    field default, not an independent named constant (`RetryPolicy.max_attempts`,
    `RateGate.rate_per_second`, ...); `_own_dataclass_fields` already records it.
    """

    own_field_names = set(cls.__dict__.get("__dataclass_fields__", {}).keys())
    for name, value in cls.__dict__.items():
        if not _is_public(name) or name in own_field_names:
            continue
        if isinstance(value, _SCALAR_CONSTANT_TYPES) and not isinstance(value, Enum):
            yield name, value


def _already_documented_names(cls: type) -> set[str]:
    """Names already recorded as a property, dataclass field, enum member or constant.

    An attribute assignment for one of these names is not emitted a second time
    (brief requirement 1): the other kind already documents it.
    """

    names = {name for name, _prop in _own_properties(cls)}
    names |= {field.name for field, _annotation, _resolved in _own_dataclass_fields(cls)}
    names |= {name for name, _value in _own_constants(cls)}
    if issubclass(cls, Enum):
        names |= set(cls.__members__.keys())
    return names


def _parameter_types(func: Any) -> dict[str, str]:
    """`{parameter name: rendered annotation}` for every parameter `func` declares.

    `self`/`cls` is stripped, mirroring `_format_callable`, so a bare `self.x = self`
    assignment cannot spuriously resolve against it.
    """

    signature, _resolved = _resolved_signature(func)
    parameters = list(signature.parameters.values())
    if parameters and parameters[0].name in ("self", "cls"):
        parameters = parameters[1:]
    return {parameter.name: render_type(parameter.annotation) for parameter in parameters}


def _render_attribute_annotation(node: ast.expr, namespace: Mapping[str, Any]) -> str:
    """An `AnnAssign` annotation, resolved and passed through `render_type`.

    On any resolution failure (a `TYPE_CHECKING`-only name, an unresolvable forward
    reference, ...) the `ast.unparse` source text is emitted verbatim instead of
    crashing (brief requirement 4a); `render_type` already passes a bare `str` through
    unchanged, so this fallback composes with it rather than duplicating it.
    """

    source = ast.unparse(node)
    try:
        expression = ast.fix_missing_locations(ast.Expression(body=node))
        value = eval(  # noqa: S307 - evaluating a class's own annotation source, not input
            compile(expression, "<attribute-annotation>", "eval"), dict(namespace)
        )
    except Exception:  # noqa: BLE001 - any resolution failure means "fall back to source text"
        return source
    try:
        return render_type(value)
    except Exception:  # noqa: BLE001 - same fallback for a render_type edge case
        return source


def _self_assignments(
    function_def: ast.FunctionDef | ast.AsyncFunctionDef,
    param_types: dict[str, str],
    namespace: Mapping[str, Any],
) -> Iterable[tuple[str, str]]:
    """`(attribute name, rendered type)` for every public `self.X = ...` in the body."""

    for node in ast.walk(function_def):
        if isinstance(node, ast.AnnAssign):
            target = node.target
            if (
                node.value is not None
                and isinstance(target, ast.Attribute)
                and isinstance(target.value, ast.Name)
                and target.value.id == "self"
                and _is_public(target.attr)
            ):
                yield target.attr, _render_attribute_annotation(node.annotation, namespace)
        elif isinstance(node, ast.Assign):
            for assign_target in node.targets:
                if not (
                    isinstance(assign_target, ast.Attribute)
                    and isinstance(assign_target.value, ast.Name)
                    and assign_target.value.id == "self"
                    and _is_public(assign_target.attr)
                ):
                    continue
                if isinstance(node.value, ast.Name) and node.value.id in param_types:
                    type_str = param_types[node.value.id]
                else:
                    type_str = _UNRESOLVED
                yield assign_target.attr, type_str


def _own_attributes(cls: type) -> Iterable[tuple[str, str]]:
    """`(attribute name, rendered type)` for every public instance attribute `cls` sets.

    Declared-only: walks the AST of `__init__` and of every other public method `cls`
    itself declares (`_own_callables`, the same `__dict__`-based convention every other
    `_own_*` helper here uses), never instantiates. First assignment wins, in
    `_own_callables`' sorted order -- `__init__` sorts first because `"_" < "a"` -- so a
    name set in both `__init__` and a later public method is documented once, from
    `__init__`.
    """

    excluded = _already_documented_names(cls)
    module = sys.modules.get(cls.__module__)
    namespace: Mapping[str, Any] = vars(module) if module is not None else {}
    seen: dict[str, str] = {}
    for name, func, _label in sorted(_own_callables(cls), key=lambda item: item[0]):
        try:
            source = textwrap.dedent(inspect.getsource(func))
            tree = ast.parse(source)
        except (OSError, TypeError, SyntaxError):
            continue
        function_def = tree.body[0]
        if not isinstance(function_def, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        param_types = _parameter_types(func)
        for attr_name, type_str in _self_assignments(function_def, param_types, namespace):
            if attr_name in excluded or attr_name in seen:
                continue
            seen[attr_name] = type_str
    return seen.items()


_KIND_MARKERS: Final[dict[inspect._ParameterKind, str]] = {
    inspect.Parameter.KEYWORD_ONLY: "kw ",
    inspect.Parameter.POSITIONAL_ONLY: "pos ",
}
_NAME_PREFIXES: Final[dict[inspect._ParameterKind, str]] = {
    inspect.Parameter.VAR_POSITIONAL: "*",
    inspect.Parameter.VAR_KEYWORD: "**",
}


def _format_parameter(parameter: inspect.Parameter) -> str:
    kind_marker = _KIND_MARKERS.get(parameter.kind, "")
    name_prefix = _NAME_PREFIXES.get(parameter.kind, "")
    optional_marker = "[opt] " if parameter.default is not inspect.Parameter.empty else ""
    type_str = render_type(parameter.annotation)
    return f"{optional_marker}{kind_marker}{name_prefix}{parameter.name}: {type_str}"


def _format_callable(name: str, func: Any, label: str) -> tuple[str, set[type]]:
    signature, resolved = _resolved_signature(func)
    parameters = list(signature.parameters.values())
    if label != "staticmethod" and parameters and parameters[0].name in ("self", "cls"):
        parameters = parameters[1:]

    referenced: set[type] = set()
    if resolved:
        for parameter in parameters:
            _collect_referenced_classes(parameter.annotation, referenced)
        _collect_referenced_classes(signature.return_annotation, referenced)

    params_str = ", ".join(_format_parameter(parameter) for parameter in parameters)
    return_str = render_type(signature.return_annotation)
    return f"{label} {name}({params_str}) -> {return_str}", referenced


def _classify(cls: type) -> str:
    if issubclass(cls, Enum):
        return "enum"
    if getattr(cls, "_is_runtime_protocol", False):
        return "runtime-checkable protocol"
    if getattr(cls, "_is_protocol", False):
        return "protocol"
    if dataclasses.is_dataclass(cls):
        frozen = bool(getattr(cls, "__dataclass_params__").frozen)
        return "frozen dataclass" if frozen else "dataclass"
    if issubclass(cls, BaseException):
        return "exception"
    return "class"


def _referenced_classes_for(cls: type) -> set[type]:
    referenced: set[type] = set()
    for name, func, label in _own_callables(cls):
        _, refs = _format_callable(name, func, label)
        referenced |= refs
    for _name, prop in _own_properties(cls):
        if prop.fget is not None:
            _, refs = _format_callable(_name, prop.fget, "property")
            referenced |= refs
    for _field, annotation, resolved in _own_dataclass_fields(cls):
        if resolved:
            _collect_referenced_classes(annotation, referenced)
    return referenced


def _closure(roots: Iterable[type]) -> set[type]:
    visited: set[type] = set()
    queue: list[type] = list(roots)
    while queue:
        cls = queue.pop()
        if cls in visited:
            continue
        visited.add(cls)
        for referenced in _referenced_classes_for(cls):
            if (
                referenced not in visited
                and _is_package_class(referenced)
                and _is_public(referenced.__qualname__.rsplit(".", 1)[-1])
            ):
                queue.append(referenced)
    return visited


def _describe_class(cls: type) -> list[str]:
    owner = _canonical_name(cls)
    lines = [f"{owner} : type {_classify(cls)}"]

    for name, func, label in sorted(_own_callables(cls), key=lambda item: item[0]):
        rendered, _ = _format_callable(name, func, label)
        lines.append(f"{owner} : {rendered}")

    for name, prop in sorted(_own_properties(cls), key=lambda item: item[0]):
        access = "get/set" if prop.fset is not None else "get"
        type_str = render_type(inspect.signature(prop.fget, eval_str=True).return_annotation) if (
            prop.fget is not None
        ) else _UNRESOLVED
        lines.append(f"{owner} : property {name} : {type_str} {{{access}}}")

    for field, annotation, _resolved in sorted(
        _own_dataclass_fields(cls), key=lambda item: item[0].name
    ):
        lines.append(f"{owner} : field {field.name} : {render_type(annotation)}")

    for name, type_str in sorted(_own_attributes(cls), key=lambda item: item[0]):
        lines.append(f"{owner} : attribute {name} : {type_str}")

    if issubclass(cls, Enum):
        for name, member in sorted(cls.__members__.items()):
            lines.append(f"{owner} : member {name} = {member.value!r}")
    else:
        for name, value in sorted(_own_constants(cls), key=lambda item: item[0]):
            lines.append(f"{owner} : const {name} = {value!r}")

    return lines


def _root_classes() -> list[type]:
    return [
        obj
        for name in _sdk.__all__
        if isinstance(obj := getattr(_sdk, name), type)
    ]


def _root_functions() -> list[tuple[str, Any]]:
    return [
        (name, obj)
        for name in _sdk.__all__
        if inspect.isfunction(obj := getattr(_sdk, name)) and not isinstance(obj, type)
    ]


def _describe_module_function(name: str, func: Any) -> tuple[list[str], set[type]]:
    label = "async function" if inspect.iscoroutinefunction(func) else "function"
    rendered, referenced = _format_callable(name, func, label)
    return [f"{_PACKAGE} : {rendered}"], referenced


def capture() -> list[str]:
    """One line per public type and public member, sorted for a stable diff."""

    classes = _closure(_root_classes())
    lines: list[str] = []
    for cls in classes:
        lines.extend(_describe_class(cls))
    for name, func in _root_functions():
        function_lines, _ = _describe_module_function(name, func)
        lines.extend(function_lines)
    return sorted(lines)


def type_count() -> int:
    return len(_closure(_root_classes()))


def render_baseline() -> str:
    return "\n".join([_HEADER, *capture()]) + "\n"


if __name__ == "__main__":
    text = render_baseline()
    if "--write" in sys.argv[1:]:
        _BASELINE_PATH.write_text(text, encoding="utf-8")
    else:
        print(text, end="")
