using System.Reflection;
using BastionVault.IntegrationSdk.Tests.Harness;

namespace BastionVault.IntegrationSdk.Tests.ApiSurface;

/// <summary>
/// The CNF-027 gate itself (D-M1b-19): a real, executing check that the compiled assembly's public
/// surface matches the committed baseline. Runs inside plain <c>dotnet test</c>, so it needs no new
/// CI step to execute — it is the mechanism <c>.github/workflows/dotnet.yml</c> now points at,
/// replacing the inert <c>Microsoft.CodeAnalysis.PublicApiAnalyzers</c> enforcement.
/// </summary>
public sealed class PublicApiSurfaceTests
{
    [Fact]
    [Requirement("CNF-027")]
    [Trait("Requirement", "CNF-027")]
    public void Compiled_assembly_surface_matches_the_committed_baseline()
    {
        FixtureRepository repository = new();
        string baselinePath = Path.Combine(
            repository.RepositoryRoot, "dotnet", "BastionVault.IntegrationSdk", "PublicApiSurface.txt");

        IReadOnlyList<string> actual = PublicApiSurfaceScanner
            .Capture(typeof(BastionVault.IntegrationSdk.SdkInfo).Assembly)
            .OrderBy(line => line, StringComparer.Ordinal)
            .ToArray();

        string[] expected = File.ReadAllLines(baselinePath)
            .Where(line => line.Length > 0 && !line.StartsWith('#'))
            .OrderBy(line => line, StringComparer.Ordinal)
            .ToArray();

        IEnumerable<string> added = actual.Except(expected, StringComparer.Ordinal);
        IEnumerable<string> removed = expected.Except(actual, StringComparer.Ordinal);

        Assert.True(
            !added.Any() && !removed.Any(),
            "Public API surface drifted from dotnet/BastionVault.IntegrationSdk/PublicApiSurface.txt.\n"
                + "Added (present in the build, missing from the baseline):\n  "
                + string.Join("\n  ", added)
                + "\nRemoved (present in the baseline, missing from the build):\n  "
                + string.Join("\n  ", removed)
                + "\nRegenerate the baseline mechanically (do not hand-edit) if this change is intended.");
    }

    [Fact]
    [Requirement("CNF-027")]
    [Trait("Requirement", "CNF-027")]
    public void Scanner_flags_a_seeded_new_public_member_as_a_gate_violation()
    {
        // D-M1b-19 / DR-0001: every gate must be proven by seeding a violation and showing it is
        // caught. This seeds one against the scanner's own comparison logic — the same logic
        // Compiled_assembly_surface_matches_the_committed_baseline runs against the real assembly —
        // without mutating the committed baseline or the real build.
        string[] baseline = { "type BastionVault.IntegrationSdk.Probe : sealed class" };
        string[] withSeededNewMember = baseline.Append("  method NewMember() -> System.Void").ToArray();

        IEnumerable<string> added = withSeededNewMember.Except(baseline, StringComparer.Ordinal);
        IEnumerable<string> removed = baseline.Except(withSeededNewMember, StringComparer.Ordinal);

        Assert.Single(added);
        Assert.Empty(removed);
        Assert.Contains("NewMember", added.Single(), StringComparison.Ordinal);
    }

    [Fact]
    [Requirement("CNF-027")]
    [Trait("Requirement", "CNF-027")]
    public void Scanner_flags_a_seeded_removed_public_member_as_a_gate_violation()
    {
        string[] baseline = { "type BastionVault.IntegrationSdk.Probe : sealed class", "  method Existing() -> System.Void" };
        string[] withRemovedMember = { "type BastionVault.IntegrationSdk.Probe : sealed class" };

        IEnumerable<string> added = withRemovedMember.Except(baseline, StringComparer.Ordinal);
        IEnumerable<string> removed = baseline.Except(withRemovedMember, StringComparer.Ordinal);

        Assert.Empty(added);
        Assert.Single(removed);
    }
}

#if GENERATE_API_SURFACE
public sealed class PublicApiSurfaceGenerator
{
    [Fact]
    public void Regenerate()
    {
        FixtureRepository repository = new();
        string baselinePath = Path.Combine(
            repository.RepositoryRoot, "dotnet", "BastionVault.IntegrationSdk", "PublicApiSurface.txt");
        IReadOnlyList<string> actual = PublicApiSurfaceScanner
            .Capture(typeof(BastionVault.IntegrationSdk.SdkInfo).Assembly)
            .OrderBy(line => line, StringComparer.Ordinal)
            .ToArray();
        File.WriteAllLines(baselinePath, new[] { "# Mechanically generated by PublicApiSurfaceScanner (D-M1b-19). Do not hand-edit." }.Concat(actual));
    }
}
#endif
